# 프로미스

ES6에서는 기존에 콜백 패턴을 대신할 또 다른 패턴 프로미스를 도입했습니다. 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이있습니다.

## 😣 **비동기의 문제점**

```jsx
const _result = null;

const get = (url) => {
  let result = null;
  const xhr = new XMLHttpRequest();

  xhr.open("GET", url);

  xhr.onload = () => {
    if (xhr.status === 200) {
      console.log(JSON.parse(xhr.response));
      result = JSON.parse(xhr.response);
      _result = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
  xhr.send();
  return message;
};

const result = get("https://jsonplaceholder.typicode.com/todos/10");
console.log(result); // 😣 null 변수 반환
console.log(_result); // 😣 null 상위 스코프
```

<aside>
💡 비동기 함수란?
함수 내부에 비동기로 동작하는 코드를 포함한 함수이다. XMLHttpRequest 객체의 onload 메소드가 비동기 함수 이다. 그래서 get함수는 비동기 함수이다.

</aside>

### 🔥 비동기함수는 비동기로 동작하는 코드가 완료되지 않아도 기다리지 않고 즉시 종료된다

1. 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하면 기대한대로 동작하지 않는다.
2. 상위 스코프의 변수에 할당해도 기대한대로 동작하지않는다.

---

```jsx
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.onload = () => {
    if (xhr.status === 200) {
      callback(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
  xhr.send();
};
```

<aside>
⚠️ 결과를 외부로 반환할 수 없고, 상위스코프의 변수에 할당할 수도없다 그래서 callback 함수를 이용하는 것이다.

</aside>

하지만 콜백함수를 써서 비동기 함수의 결과값을 받을 수 있게되었지만 콜백 함수 안에서 비동기함수를 계속 호출하게 된다면 `콜백 헬(callback hell)` 현상이 나타나서 복잡도가 높아진다.

```jsx
get("https://jsonplaceholder.typicode.com/todos/10", (user_id) => {
  get("https://jsonplaceholder.typicode.com/todos/11", (user_info) => {
    get("https://jsonplaceholder.typicode.com/todos/12", (user_name) => {
      get("https://jsonplaceholder.typicode.com/todos/13", (user_jop) => {
        console.log(JSON.parse(user_id));
        console.log(JSON.parse(user_info));
        console.log(JSON.parse(user_name));
        console.log(JSON.parse(user_jop));
      });
    });
  });
});
```

콜백함수가 2뎁스를 들어가도 복잡한데 3뎁스, 4뎁스 계속 뎁스가 깊어진다면 코드 `가독성`은 나뻐지고 실수를 유발하고 오류가 발생된다면 `디버그`를 하기 힘들어진다.

## 😣 콜백함수의 에러처리 한계

```jsx
try {
  setTimeout(() => {
    throw new Error("강제 발생");
  }, 1000);
} catch (error) {
  console.error(error); // 에러를 잡지 못한다.
}
```

콜백함수에서 에러가 발생되어도 try/catch문을 이용해서 에러를 핸들링 할 수 없는 문제가 있다.

### 에러를 잡지 못하는이유?

setTimeout의 `실행컨텍스트`는 생성이된다. setTimeout은 비동기 함수여서 즉시 종료가 되고 `실행컨텍스트 스택` 에서 제거가 된다. 이후 타이머의 시간이 초과되면 `콜백 함수` 는 `태스크 큐`로 푸쉬 되고 `실행컨텍스트 스택`이 비워 질때까지 기다리다가 비워지면 `실행컨텍스트 스택` 에 푸쉬를하고 실행을 한다. `에러는 호출자 방향`(caller) 으로 전파가 된다. 이때 콜백함수의 호출자(caller)는 `setTimeout` 이 아니다. 이미 `setTimeout` 의 호출은 종료되었다. 그래서 `setTimeout` 의 `try/catch문` 이 작동하지 않는 이유이다.

```jsx
index.js:29 Uncaught Error: 강제 발생
    at index.js:29:11
```

<aside>
⚠️ 강제로 발생한 에러는 catch하지 못하여서 전역으로 전파되어버렸다. 그래서 잡히지 않는에러 (Uncaugth Error) 러가 발생한 것이다.

</aside>

---

## 👍 콜백함수의 한계로 나온 프로미스

프로미스는 ECMAscript 사양에 정의 된 표준 빌트인 객체입니다.

```jsx
const promise = new Promise((resolve, reject) => {
  let num = 999;
  if (num > 1) resolve("비동기 성공");
  else reject("비동기 실패");
});
```

프로미스 생성자 함수에 인자 값으로 resolve(성공), reject(실패)를 매개변수로 받는 콜백함수를 넣어주면 생성이 가능하다.

```jsx
const promiseGet = (url) => {
  return new Promise((res, rej) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.onload = () => {
      if (xhr.status === 200) {
        res(JSON.parse(xhr.response));
      } else {
        rej(`${xhr.status} ${xhr.statusText}`);
      }
    };
    xhr.send();
  });
};

promiseGet("https://jsonplaceholder.typicode.com/todos/10").then((response) => {
  console.log(response);
});
```

| 프로미스의 상태 | 의미                                  | 상태 변경 조건                   |
| --------------- | ------------------------------------- | -------------------------------- |
| pendding        | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled       | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected        | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

### Resolve 시나리오

| 프로미스 |          |
| -------- | -------- |
| status   | pendding |
| result   | undfined |

| 프로미스 |           |
| -------- | --------- |
| status   | fulfilled |
| result   | value     |

```jsx
const fulfilled = new Promise((res) => res("성공"));
console.log(fulfilled);

Promise {<fulfilled>: '성공'}
[[Prototype]]: Promise
[[PromiseState]]: "fulfilled"
[[PromiseResult]]: "성공"
```

### Rejected 시나리오

| 프로미스 |          |
| -------- | -------- |
| status   | pendding |
| result   | undfined |

| 프로미스 |          |
| -------- | -------- |
| status   | rejected |
| result   | error    |

```jsx
const rejected = new Promise((_, rej) => rej("실패"));
console.log(rejected);

Promise {<rejected>: '실패'}
[[Prototype]]: Promise
[[PromiseState]]: "rejected"
[[PromiseResult]]: "실패"
```

<aside>
💡 `settled` 상태가 있다 `settled` 상태는 성공, 실패 상관없이 `pendding`상태가 아닌 걸 의미한다.

</aside>

### 📚 프로미스 처리 메소드

프로미스의 비동기 처리 상태(**fullfiled, rejected**)가 변화하면 후속 처리 메서드(**resovle, reject**)에 인수로 전달한 콜백 함수가 선택적으로 호출된다.

### 프로토타입 메소드들

1. **then**

```jsx
1;
new Promise((resolve) => resolve("성공")).then((response) =>
  console.log(response)
); // 성공

2;
new Promise((resolve) => resolve("성공"))
  .then((response) => {
    console.log(response);
    return new Promise((resolve) => resolve("성공2"));
  })
  .then((response) => console.log(response));

3;
new Promise((resolve) => resolve("성공"))
  .then((response) => {
    console.log(response);
    return "성공2";
  })
  .then((response) => console.log(response));

new Promise((resolve) => resolve("성공")).then(
  (response) => console.log(response),
  (error) => console.error(error)
);
```

then메소드는 두개의 콜백 함수를 인자로 받는데 첫번째 인자는 `resolve함수` 호출 시 넘겨주는 값을 받을 수 있다. 두번째 인자는 `reject함수` 호출 시 넘겨주는 값을 받을 수 있다.

then메소드의 콜백 함수가 프로미스 또는 값을 반환하면 프로미스체인으로 다음 then메소드를 호출 할 수 있다**(예제1,예제2)**.

---

1. **catch**

```jsx
1;
new Promise((_, reject) => reject("실패")).catch((error) =>
  console.error(error)
);

2;
new Promise((_, reject) => reject("실패"))
  .catch((error) => {
    console.error(error);
    throw new Error("실패2");
  })
  .then(
    () => {},
    (error) => console.error("여기에 에러 캐치", error)
  );

3;
new Promise((_, reject) => reject("실패"))
  .catch((error) => {
    console.error(error);
    throw new Error("실패2");
  })
  .catch((error) => console.error("여기에 에러 캐치", error));
```

catch메소드는 한개의 콜백 함수를 인수로 받는다. `reject함수` 가 호출 되고 `rejecte상태` 일때 메소드가 호출 됩니다.

콜백 함수가 프로미스 또는 값을 반환하면 then을 호출하고 Error객체를 throw하면 then의 두번째 인자 콜백 함수를 호출하거나 catch메소드를 호출합니다.

2번째 방식은 사용하기가 불편하고 코드가 복잡해지고 가독성이 안좋다. 지양하고 catch메소드를 사용해야 된다.

<aside>
📌  **catch 메소드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에 발생한 에러뿐(rejected상태)뿐만 아니라 then메소드 내부에서 발생한 에러도 핸들링이 가능하다.**

</aside>

1. **finally**

```jsx
new Promise((resolve) => resolve("성공"))
  .then((success) => {
    console.log(success);
    throw new Error("실패2");
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    console.log("성공 실패 상관없이 실행된다.");
  });
```

프로미스의 상태에 상관없이 무조건 실행되는 메소드입니다.

### 프로미스 체이닝

```jsx
new Promise((resolve) => resolve("성공"))
  .then((success) => Promise.resolve(success)) // 성공
  .then((success) => console.log(success)) // undefined
  .then((success) => console.log(success)) // undefined
  .catch((error) => console.error(error)) // 에러가 발생하지 않으면 실행 x
  .finally(() => console.log("성공 실패 상관없이 실행된다."));
```

### 정적 메소드들

1. Promise.resolve

```jsx
const resovlePromise = Promise.resolve("성공");
resovlePromise.then((success) => console.log(success)); // 성공
```

이미 값은 있는데 Promise로 래핑해서 보내야 될 때 사용합니다.

1. Promise.reject

```jsx
const rejectPromise = Promise.reject("실패");
rejectPromise.catch((error) => console.log(error));
```

이미 에러 값은 있는데 Promise로 래핑해서 보내야 될 때 사용합니다.

1. Promise.all

```jsx
const promises = Promise.all([
  new Promise((resovle) => resovle("성공1")),
  new Promise((resovle) => resovle("성공2")),
  new Promise((resovle) => resovle("성공3")),
]);
promises.then((responses) => console.log(responses)); // [ '성공1', '성공2', '성공3' ]

const promises = Promise.all([
  new Promise((resovle) => resovle("성공1")),
  new Promise((_, reject) => reject("실패2")),
  new Promise((resovle) => resovle("성공3")),
]);
promises
  .then((responses) => console.log(responses))
  .catch((error) => console.error(error)); // 실패2
```

프로미스를 요소로 갖는 배열을 인수로 전달한다. 여러 개의 프로미스를 모두 병렬 처리를 해서 보낸다. 비동기 처리가 모두 `fulfilled 상태`가 되면 `then메소드` 호출로 값을 받을 수 있다.

<aside>
📌 Promise.all은 하나라도 실패(rejected)하면 나머지 비동기 처리를 기다리지 않고 바로 종료하고 error를 반환한다.

</aside>

1. Promise.race

```jsx
const promisesRace = Promise.race([
  new Promise((resolve) => setTimeout(() => resolve("지연 2초"), 2000)),
  new Promise((resolve) => setTimeout(() => resolve("지연 1초"), 1000)),
  new Promise((resolve) => setTimeout(() => resolve("지연 3초"), 3000)),
]);
promises.then((responses) => console.log(responses));

const promisesRace = Promise.race([
  new Promise((resolve) => setTimeout(() => resolve("지연 2초"), 2000)),
  new Promise((_, reject) => setTimeout(() => reject("지연 1초"), 1000)),
  new Promise((resolve) => setTimeout(() => resolve("지연 3초"), 3000)),
]);
promisesRace
  .then((responses) => console.log(responses))
  .catch((error) => console.error(error)); // 지연 1초
```

Promise.all 처럼 프로미스 요소를 갖는 배열을 인자로 전달 받는다. 병렬 처리로 하고 제일 빠르게 도착한 비동기 처리를 반환해준다. Promise.all 처럼 `실패(rejected상태)`가 되면 나머지 비동기 처리를 기다리지 않고 바로 에러를 반환한다.

1. Promise.allSettled

```jsx
const promisesAllSettled = Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve("지연 2초"), 2000)),
  new Promise((_, reject) => setTimeout(() => reject("지연 1초"), 1000)),
  new Promise((resolve) => setTimeout(() => resolve("지연 1초"), 3000)),
]);
promisesAllSettled.then((responses) => console.log(responses));

[
  { status: "fulfilled", value: "지연 2초" },
  { status: "rejected", reason: "지연 1초" },
  { status: "fulfilled", value: "지연 1초" },
];
```

ES11에 도입된 메소드입니다. `Promise.all, race` 처럼 프로미스 요소를 갖는 배열을 인자로 전달 받는다. all, race와 다른점은 `실패(rejected)`를 하여도 나머지 비동기 처리를 기다리고 `status 프로퍼티`의 값에 상태를 구별해서 반환해준다. 성공하면 value 프로퍼티를 갖고 실패하면 reason 프로퍼티를 갖는다.
